steps:
  - name: "node:18"
    entrypoint: npm
    args: ["install"]
  - name: "node:18"
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - 'GITHUB_APP_ID=${_GITHUB_APP_ID}'
      - 'GITHUB_APP_NAME=${_GITHUB_APP_NAME}'
      - 'GITHUB_APP_CLIENT_ID=${_GITHUB_APP_CLIENT_ID}'
      - 'GITHUB_APP_CLIENT_SECRET=${_GITHUB_APP_CLIENT_SECRET}'
      - 'SQLITE_URL=${_SQLITE_URL}'
      - 'SQLITE_AUTH_TOKEN=${_SQLITE_AUTH_TOKEN}'
      - 'GITHUB_APP_PRIVATE_KEY=${_GITHUB_APP_PRIVATE_KEY}'
  - name: "node:18"
    entrypoint: npm
    args: ["run", "build"]      
  - name: "node:18"
    entrypoint: npm
    args: ['run', 'test']
  - name: "node:18"
    entrypoint: npm
    args: ["run", "db:migrate"]    
  - name: "node:18"
    entrypoint: npm
    args: ["run", "start"]
options:
  logging: CLOUD_LOGGING_ONLY    
timeout: "1800s"